services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    user: "$PID:$GID"
  influxdb:
    image: influxdb:2
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    env_file:
      - .env
  telegraf:
    image: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - .env
    depends_on:
      - influxdb
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
  mosquitto-subscriber:
    image: eclipse-mosquitto
    command: ["mosquitto_sub", "-h", "mosquitto", "-t", "test"]
    depends_on:
      - mosquitto
